### ISSUE TITLE
Add SSH support

### ISSUE THREAD

**Issue by nickpegg** [nickpegg/ciscolib#4]
Telnet is horribly insecure, so ciscolib should have support for SSH connections. Probably a good idea to split Device into two classes: TelnetDevice and SSHDevice

I've actually already started work on this at my job, hopefully I'll be able open-source those changes.

**Comment by supergua** [comment]
hi, how about this work?

**Comment by nickpegg** [comment]
Hey! This project is deprecated in favor of other Python libraries which are much more full-featured (see the [README](https://github.com/nickpegg/ciscolib#deprecation-notice) for links to those). All of those have full SSH support for a myriad of devices (not just Cisco!) and have a boatload of other useful features.
